package dubby.serve.xfood.util.constants;
/**
 * Here lies all app constants
 */
public enum AppConstant {

    USER_REGISTERED_MESSAGE,
    BAD_EMAIL_FORMAT_MESSAGE,
    BAD_MOBILE_NUMBER_MESSAGE,
    EMAIL_IN_USE_MESSAGE,
    USERNAME_TAKEN_MESSAGE,
    EMAIL_NOT_SENT_MESSAGE,
    MOBILE_NUMBER_IN_USE_MESSAGE,
    CONTACT_DETAILS_REQUIRED_MESSAGE,
    VERIFICATION_REASON_MESSAGE,
    UNRECOGNIZED_IP_MESSAGE,
    IP_ADDRESS_REGEX,
    USER_REGISTRATION_SUBJECT,
    USER_REGISTRATION_FRONTEND_URL,
    ENTITY_CONSTRAINT_MESSAGE,
    ENTITY_NULL_MESSAGE

}
